src/main/java/stripesdemo/model/Model.java
package stripesdemo.model;

public class Model {
	
	private Long id;
	private String property1;
	private String property2;
	
	public Model(){};
	
	public Long getId() { return id; }
	/*package*/ void setId(Long id) { this.id = id; }
	
	public String getProperty1() { return property1; }
	public void setProperty1(String property1) { this.property1 = property1; }
	
	public String getProperty2() { return property2; }
	public void setProperty2(String property2) { this.property2 = property2; }

}

src/main/java/stripesdemo/model/SomeRepo.java

package stripesdemo.model;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class SomeRepo {
	
	private static SomeRepo instance;
	private SomeRepo(){};
	
	public static SomeRepo getInstance(){
		if(instance == null){
			instance = new SomeRepo();
		}
		return instance;
	}
	
	private Map<Long, Model> dbTable = new HashMap<Long, Model>();
	
	public Model get(Long id){
		if(id == null)
			return null;
		
		return dbTable.get(id);
	}
	
	public void saveOrUpdate(Model model){
		if(model == null)
			return;
		if(model.getId() == null){
			model.setId(new Long(dbTable.size()));
		}
		dbTable.put(model.getId(), model);
	}
	
	public List<Model> getAllModels(){
		return new ArrayList<Model>(dbTable.values());
	}
	
}

src/main/java/stripesdemo/action/BaseActionBean.java
package stripesdemo.action;

import javax.servlet.http.HttpSession;

import org.apache.log4j.Logger;

import net.sourceforge.stripes.action.ActionBean;
import net.sourceforge.stripes.action.ActionBeanContext;
import net.sourceforge.stripes.action.DefaultHandler;
import net.sourceforge.stripes.action.Resolution;
import net.sourceforge.stripes.action.SimpleMessage;
import net.sourceforge.stripes.action.UrlBinding;
import net.sourceforge.stripes.validation.SimpleError;

public abstract class BaseActionBean implements ActionBean {
	protected Logger log = Logger.getLogger(BaseActionBean.class);

	private ActionBeanContext context;

	public ActionBeanContext getContext() {return context;}
	public void setContext(ActionBeanContext context) {this.context = context;}

	/**
	 * Just a simple shortcut to the current session. (only here to make
	 * expressions shorter). - Doesn't Make any test if there is a context OR a
	 * request -
	 */
	protected HttpSession getSession() {
		return getContext().getRequest().getSession();
	}
	
	public String getTitle() {
		return "Stripes Demo";
	}
	
	public final String getUrlBinding() {
		if (getClass() != null && getClass().getAnnotation(UrlBinding.class) != null) {
			return getClass().getAnnotation(UrlBinding.class).value();
		}
		return null;
	}

	
	public void addError(String error){
		getContext().getValidationErrors().addGlobalError(new SimpleError(error));
	}
	
	public void addMessage(String message){
		getContext().getMessages().add(new SimpleMessage(message));
	}
	
	public final String getClassName() {
		return this.getClass().getName();
	}
	
	@DefaultHandler
	public abstract Resolution defaultAction();
	
	
}

src/main/java/stripesdemo/action/HomeActionBean.java
package stripesdemo.action;

import net.sourceforge.stripes.action.DefaultHandler;
import net.sourceforge.stripes.action.ForwardResolution;
import net.sourceforge.stripes.action.Resolution;
import net.sourceforge.stripes.action.UrlBinding;

@UrlBinding("/home.ext")
public class HomeActionBean extends BaseActionBean {
	private static String JSP = "/WEB-INF/stripes/home.jsp";
	
	@DefaultHandler
	public Resolution defaultAction() {
		return new ForwardResolution(JSP);
	}
}

src/main/java/stripesdemo/action/ModelActionBean.java
package stripesdemo.action;

import java.util.List;

import net.sourceforge.stripes.action.Before;
import net.sourceforge.stripes.action.DefaultHandler;
import net.sourceforge.stripes.action.ForwardResolution;
import net.sourceforge.stripes.action.RedirectResolution;
import net.sourceforge.stripes.action.Resolution;
import net.sourceforge.stripes.action.UrlBinding;
import net.sourceforge.stripes.validation.Validate;
import net.sourceforge.stripes.validation.ValidationErrorHandler;
import net.sourceforge.stripes.validation.ValidationErrors;
import net.sourceforge.stripes.validation.ValidationMethod;
import stripesdemo.model.Model;
import stripesdemo.model.SomeRepo;

@UrlBinding("/model.ext")
public class ModelActionBean extends BaseActionBean implements ValidationErrorHandler{
	private static String JSP = "/WEB-INF/stripes/model.jsp";
	
	@Before(on="defaultAction")
	public void load(){
		if(getId() != null){
			Model model = SomeRepo.getInstance().get(getId());
			setProperty1(model.getProperty1());
			setProperty2(model.getProperty2());
		}
	}
	
	@DefaultHandler
	public Resolution defaultAction() {
		return new ForwardResolution(JSP);
	}
	
	//Custom validation -- happens AFTER automatic validation
	@ValidationMethod(on="save")
	public void validateSave(){
		if("Bobby".equals(getProperty1())){
			addError("Nein! Nein! This is an error!!!");
		}
	}
	
	public Resolution save(){
		Model model = new Model();
		
		if(getId()!= null)
			model = SomeRepo.getInstance().get(getId());
		
		model.setProperty1(getProperty1());
		model.setProperty2(getProperty2());
		
		SomeRepo.getInstance().saveOrUpdate(model);
		
		addMessage("Success!!");
		
		return new RedirectResolution(this.getUrlBinding()).addParameter("id", getId());
	}
	
	public Resolution handleValidationErrors(ValidationErrors errors) throws Exception {
		//in case of error, nothing special, we go back to the default action
		return defaultAction();
	}
	
	private Long id;
	private String property1;
	private String property2;
	
	public Long getId() { return id; }
	public void setId(Long id) { this.id = id; }
	
	//Automatic validation when saving.
	@Validate(on="save", required=true)
	public String getProperty1() {return property1;}
	public void setProperty1(String property1) {this.property1 = property1;}

	@Validate(on="save", required=true)
	public String getProperty2() {return property2;}
	public void setProperty2(String property2) {this.property2 = property2;}

	public List<Model> getModels(){
		return SomeRepo.getInstance().getAllModels();
	}
}

src/main/java/stripesdemo/action/Page1ActionBean.java
package stripesdemo.action;

import net.sourceforge.stripes.action.DefaultHandler;
import net.sourceforge.stripes.action.ForwardResolution;
import net.sourceforge.stripes.action.Resolution;
import net.sourceforge.stripes.action.UrlBinding;

@UrlBinding("/page1.ext")
public class Page1ActionBean extends BaseActionBean{
	private static String JSP = "/WEB-INF/stripes/page1.jsp";
	
	@DefaultHandler
	public Resolution defaultAction() {
		return new ForwardResolution(JSP);
	}
}

src/main/java/stripesdemo/action/Page2ActionBean.java
package stripesdemo.action;

import net.sourceforge.stripes.action.DefaultHandler;
import net.sourceforge.stripes.action.ForwardResolution;
import net.sourceforge.stripes.action.Resolution;
import net.sourceforge.stripes.action.UrlBinding;

@UrlBinding("/page2.ext")
public class Page2ActionBean extends BaseActionBean{
	private static String JSP = "/WEB-INF/stripes/page2.jsp";
	
	@DefaultHandler
	public Resolution defaultAction() {
		return new ForwardResolution(JSP);
	}
}

src/main/webapp/WEB-INF/stripes/home.jsp
<%@ include file="/WEB-INF/stripes/layout/taglibs.jsp" %>

<s:layout-render name="/WEB-INF/stripes/layout/layout.jsp">
	<s:layout-component name="contents">
		
		<p>
			pulvinar pellentesque lorem, sit amet eleifend ipsum dapibus vitae. 
			Ut efficitur in mi eget pellentesque. Etiam dignissim odio nibh, id pharetra 
			turpis ornare vel. Vivamus vitae est finibus, sollicitudin erat in, dapibus 
			dolor. Vivamus dignissim enim sed neque tempus, et blandit nisl bibendum. 
			Aenean quam dolor, dapibus non egestas ac, dapibus quis sem. Mauris porttitor 
			scelerisque ante in laoreet. Curabitur magna neque, egestas a libero quis, lobortis 
			porta dui. Donec mattis turpis et quam ultricies interdum. Nullam at dolor erat. In 
			ultrices, nisl at hendrerit suscipit, nisl massa faucibus purus, vel auctor turpis 
			odio at neque. Aenean eu urna ut ex tristique congue. Quisque odio ex, aliquam ut 
			justo ac, blandit tempus metus. Morbi porta varius turpis non rutrum.
		</p>
		
	</s:layout-component>
</s:layout-render>

src/main/webapp/WEB-INF/stripes/layout/footer.jsp
<%@ include file="/WEB-INF/stripes/layout/taglibs.jsp" %>

<h1>Footer</h1>

<p> Some footer info </p>

src/main/webapp/WEB-INF/stripes/layout/layout.jsp
<%@ include file="/WEB-INF/stripes/layout/taglibs.jsp" %>
<%@ page trimDirectiveWhitespaces="true" %>
<s:layout-definition>

<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
<!-- 	<meta name="viewport" content="width=device-width, initial-scale=1"> -->
	<link rel="icon" href="img/favicon.ico">
	
	<link rel="stylesheet" href="lib/w3css/w3.css" type="text/css" />
	<link rel="stylesheet" href="lib/font-awesome/css/font-awesome.css"/>
	
	<link rel="stylesheet" href="css/w3-custom.css" type="text/css" />
	<link rel="stylesheet" href="css/w3-theme-darcula.css" type="text/css" />
	
	<s:layout-component name="htmlHead"/>
</head>
<body class="w3-theme-d4">

	<div id="page">
		<header >
			<div  class="w3-container">
				<div class="w3-row">
					<div class="w3-col s12 m3">
						<h2>
							A Site Title
						</h2>
					</div>
					<div class="w3-col s12 m8"> 
						<jsp:include page="menu.jsp"/>
					</div>
				</div>
			</div>
		</header>
		
		<section id="pageSection" class="w3-theme-d3 w3-card-4" >
			<div class="w3-container ">
				<div class="w3-row">
					<div class="w3-col m1 l2">
						&nbsp;
					</div>
					<div class="w3-col m10 l8">
						<s:messages/>
						<s:errors/>
					</div>
				</div>
			</div>
			<div  class="w3-container ">
				<div class="w3-row">
					<div class="w3-col m1 l2">
						&nbsp;
					</div>
					<div class="w3-col m10 l8">
						<article class="w3-container">
							<s:layout-component name="contents"/>
						</article>
					</div>
				</div>
			</div>
		</section>
	
	</div>  <!-- end of div page -->
	
	<div id="pageFooter" class="w3-container">
		
		<div  class="w3-container">
			<div class="w3-row">
				<div class="w3-col m1 l2">
					&nbsp;
				</div>
				<div class="w3-col m10 l8">
					<jsp:include page="footer.jsp"/>
				</div>
			</div>
		</div>
		
	</div>
</body>
</html>
</s:layout-definition>

src/main/webapp/WEB-INF/stripes/layout/menu.jsp
<%@ include file="/WEB-INF/stripes/layout/taglibs.jsp" %>

<nav class="w3-topnav">
	<c:set var="currentUrl" value="${actionBean.urlBinding }"/>

	<s:link beanclass="stripesdemo.action.HomeActionBean"   class="${ currentUrl eq '/home.ext'  ? 'w3-theme-action w3-card-2' : ''}">Home</s:link>
	<s:link beanclass="stripesdemo.action.Page1ActionBean"  class="${ currentUrl eq '/page1.ext' ? 'w3-theme-action w3-card-2' : ''}">Page 1</s:link>
	<s:link beanclass="stripesdemo.action.Page2ActionBean"  class="${ currentUrl eq '/page2.ext' ? 'w3-theme-action w3-card-2' : ''}">Page 2</s:link>
	<s:link beanclass="stripesdemo.action.ModelActionBean"  class="${ currentUrl eq '/model.ext'  ? 'w3-theme-action w3-card-2' : ''}">Model Form</s:link>
</nav>

src/main/webapp/WEB-INF/stripes/layout/taglibs.jsp
<%@ page contentType="text/html;charset=UTF-8" language="java"%>

<%@ taglib prefix="s" uri="http://stripes.sourceforge.net/stripes.tld"%>
<%@ taglib prefix="sdyn" uri="http://stripes.sourceforge.net/stripes-dynattr.tld" %>

<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt" %>
<%@ taglib prefix="fn" uri="http://java.sun.com/jsp/jstl/functions" %>

src/main/webapp/WEB-INF/stripes/model.jsp
<%@ include file="/WEB-INF/stripes/layout/taglibs.jsp" %>

<s:layout-render name="/WEB-INF/stripes/layout/layout.jsp">
	<s:layout-component name="contents">
		
		<h1>Editing</h1>
		<s:form beanclass="${actionBean.className }">
			<s:hidden name="id" />
			
			<p>
				Property1 must never be equal to 'Bobby'.
			</p>
			
			<sdyn:text name="property1" placeholder="Enter value for property1"/><br/>
			<sdyn:text name="property2" placeholder="Enter value for property2"/>
			
			<s:submit name="save">Save</s:submit>
		</s:form>
		
		<h1>List</h1>
		
		<c:if test="${fn:length(actionBean.models) le 0 }">
			No model saved yet...
		</c:if>
		<c:if test="${fn:length(actionBean.models) gt 0 }">
			<table>
				<tr>
					<th>id</th>
					<th>Property 1</th>
					<th>Property 2</th>
				</tr>
				<c:forEach items="${actionBean.models }" var="model">
					<tr>
						<td>
							<s:link beanclass="${actionBean.className }">
								${model.id }
								<s:param name="id" value="${model.id }" />
							</s:link>
						</td>
						<td>${model.property1 }</td>
						<td>${model.property2 }</td>
					</tr>
				</c:forEach>
			</table>
		</c:if>

		
	</s:layout-component>
</s:layout-render>

src/main/webapp/WEB-INF/stripes/page1.jsp
<%@ include file="/WEB-INF/stripes/layout/taglibs.jsp" %>

<s:layout-render name="/WEB-INF/stripes/layout/layout.jsp">
	<s:layout-component name="contents">
		<h1>Page 1</h1>
		
		<p>
			pulvinar pellentesque lorem, sit amet eleifend ipsum dapibus vitae. 
			Ut efficitur in mi eget pellentesque. Etiam dignissim odio nibh, id pharetra 
			turpis ornare vel. Vivamus vitae est finibus, sollicitudin erat in, dapibus 
			dolor. Vivamus dignissim enim sed neque tempus, et blandit nisl bibendum. 
			Aenean quam dolor, dapibus non egestas ac, dapibus quis sem. Mauris porttitor 
			scelerisque ante in laoreet. Curabitur magna neque, egestas a libero quis, lobortis 
			porta dui. Donec mattis turpis et quam ultricies interdum. Nullam at dolor erat. In 
			ultrices, nisl at hendrerit suscipit, nisl massa faucibus purus, vel auctor turpis 
			odio at neque. Aenean eu urna ut ex tristique congue. Quisque odio ex, aliquam ut 
			justo ac, blandit tempus metus. Morbi porta varius turpis non rutrum.
		</p>
		
	</s:layout-component>
</s:layout-render>

src/main/webapp/WEB-INF/stripes/page2.jsp
<%@ include file="/WEB-INF/stripes/layout/taglibs.jsp" %>

<s:layout-render name="/WEB-INF/stripes/layout/layout.jsp">
	<s:layout-component name="contents">
		<h1>Page 2</h1>
		
		<p>
			pulvinar pellentesque lorem, sit amet eleifend ipsum dapibus vitae. 
			Ut efficitur in mi eget pellentesque. Etiam dignissim odio nibh, id pharetra 
			turpis ornare vel. Vivamus vitae est finibus, sollicitudin erat in, dapibus 
			dolor. Vivamus dignissim enim sed neque tempus, et blandit nisl bibendum. 
			Aenean quam dolor, dapibus non egestas ac, dapibus quis sem. Mauris porttitor 
			scelerisque ante in laoreet. Curabitur magna neque, egestas a libero quis, lobortis 
			porta dui. Donec mattis turpis et quam ultricies interdum. Nullam at dolor erat. In 
			ultrices, nisl at hendrerit suscipit, nisl massa faucibus purus, vel auctor turpis 
			odio at neque. Aenean eu urna ut ex tristique congue. Quisque odio ex, aliquam ut 
			justo ac, blandit tempus metus. Morbi porta varius turpis non rutrum.
		</p>
		
	</s:layout-component>
</s:layout-render>